basePath: /
host: localhost:8080
info:
  contact: {}
  description: API for Lima CLM management.
  title: Lima CLM API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns the current operational status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: API health check
      tags:
      - Health
swagger: "2.0"
